/**
 * Rebuild slugs for blogs whose slug carries no words.
 *
 * Slugs used to be generated by stripping everything outside [a-z0-9], so every
 * Hindi-titled post ended up as "-", "--1", "--2" - URLs with none of the words
 * anyone searches for. lib/slug.ts now keeps Unicode, but existing rows still
 * hold the old values and nothing rewrites them on its own.
 *
 * Dry run (prints what it would change, writes nothing):
 *   node scripts/fix-slugs.mjs
 *
 * Apply:
 *   node scripts/fix-slugs.mjs --apply
 *
 * Changing a slug changes the article's URL. Old /blogs/<old-slug> links stop
 * resolving, but /blogs/<id> links keep working - the route resolves either -
 * and the listing pages link by id, so internal navigation is unaffected.
 */
import "dotenv/config";
import mongoose from "mongoose";

const APPLY = process.argv.includes("--apply");

// Kept in step with lib/slug.ts.
function generateSlug(text) {
  return (text || "")
    .toLowerCase()
    .normalize("NFC")
    .replace(/[^\p{L}\p{N}\p{M}]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .substring(0, 100)
    .replace(/-+$/, "");
}

// For this migration the bar is words, not merely characters: "--1" and "--2"
// contain a digit but are just as unsearchable as "-".
function slugHasWords(slug) {
  return !!slug && /\p{L}/u.test(slug);
}

if (!process.env.MONGODB_URI) {
  console.error("MONGODB_URI is not set - check .env / .env.local");
  process.exit(1);
}

await mongoose.connect(process.env.MONGODB_URI, {
  serverSelectionTimeoutMS: 30000,
});

const blogs = mongoose.connection.db.collection("blogs");
const all = await blogs
  .find({}, { projection: { title: 1, slug: 1 } })
  .toArray();

const taken = new Set(all.map((b) => b.slug).filter(Boolean));
const changes = [];

for (const blog of all) {
  if (slugHasWords(blog.slug)) continue;

  const base = generateSlug(blog.title);
  if (!base) {
    console.warn(`! ${blog._id}: title yields no slug, leaving as "${blog.slug}"`);
    continue;
  }

  let candidate = base;
  let n = 1;
  while (taken.has(candidate)) candidate = `${base}-${n++}`;

  taken.delete(blog.slug);
  taken.add(candidate);
  changes.push({ _id: blog._id, from: blog.slug, to: candidate, title: blog.title });
}

if (changes.length === 0) {
  console.log("Every blog already has a usable slug - nothing to do.");
} else {
  console.log(`${changes.length} slug(s) to rewrite:\n`);
  for (const c of changes) {
    console.log(`  ${c.title.slice(0, 60)}`);
    console.log(`    "${c.from}"  ->  "${c.to}"`);
    console.log(`    /blogs/${encodeURIComponent(c.to)}\n`);
  }

  if (APPLY) {
    for (const c of changes) {
      await blogs.updateOne({ _id: c._id }, { $set: { slug: c.to } });
    }
    console.log(`Applied ${changes.length} change(s).`);
    console.log("Resubmit the sitemap in Google Search Console so the new URLs are picked up.");
  } else {
    console.log("Dry run - nothing written. Re-run with --apply to write these.");
  }
}

await mongoose.disconnect();
