import { Metadata } from "next";
import connectDB from "@/lib/mongodb";
import Blog from "@/models/Blog";
import { publishedBlogFilter } from "@/lib/blogLookup";
import { SITE_URL } from "@/lib/siteUrl";
import { isUsableSlug } from "@/lib/slug";

interface BlogMetaSource {
  _id: { toString(): string };
  title: string;
  slug?: string;
  excerpt: string;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    metaKeywords?: string[];
  };
  author?: {
    _id?: { toString(): string };
    name?: string;
  };
  publishedAt?: Date;
  updatedAt: Date;
  category: string;
  tags: string[];
  featuredImage?: string;
}

const NOT_FOUND: Metadata = {
  title: "Blog Not Found | Sanatan Blogs",
  description: "The requested blog post could not be found.",
  robots: {
    index: false,
    follow: true,
  },
};

/**
 * An article is reachable both as /blogs/<id> and /blogs/<slug> - the listing
 * pages link by id while the sitemap and related-article links use the slug.
 * Whichever URL a visitor arrives on, the canonical has to name one of them, or
 * Google sees two URLs serving identical content and splits the ranking signals
 * between them.
 *
 * The slug is the better choice because it carries the words people search for,
 * but slugs are generated by stripping everything outside [a-z0-9], so a title
 * written in Hindi produces a slug with no letters left in it. Those fall back
 * to the id rather than canonicalising to a meaningless URL.
 */
function canonicalPathFor(blog: { _id: { toString(): string }; slug?: string }) {
  const slug = blog.slug?.trim();

  return `/blogs/${isUsableSlug(slug) ? slug : blog._id.toString()}`;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  try {
    const { id } = await params;

    // Read straight from the database. This used to fetch the site's own HTTP
    // API, which meant the server called itself over the network on every
    // render - and pointed at whatever SITE_URL said, so it broke outright
    // whenever that did not match the port the server was actually listening on.
    await connectDB();

    const blog = await Blog.findOne(publishedBlogFilter(id))
      .select(
        "title slug excerpt seo author publishedAt updatedAt category tags featuredImage",
      )
      .populate("author", "name")
      .lean<BlogMetaSource | null>();

    if (!blog) return NOT_FOUND;

    const canonical = canonicalPathFor(blog);
    const shareUrl = `${SITE_URL}${canonical}`;
    const imageUrl = blog.featuredImage || `${SITE_URL}/og-image.jpg`;

    // Truncate description to optimal length (150-160 characters for best SEO)
    const metaDescription = blog.seo?.metaDescription || blog.excerpt || "";
    const truncatedDescription =
      metaDescription.length > 155
        ? `${metaDescription.substring(0, 152)}...`
        : metaDescription;

    // Generate focus keywords from title and tags
    const focusKeywords = [
      blog.title,
      ...(blog.tags || []),
      blog.category,
      "Sanatan Dharma",
      "spiritual wisdom",
    ].slice(0, 10);

    const authorName = blog.author?.name || "Sanatan Blogs";
    const publishedTime = (blog.publishedAt || blog.updatedAt)?.toISOString();
    const modifiedTime = blog.updatedAt?.toISOString();

    return {
      title: blog.seo?.metaTitle || `${blog.title} | Sanatan Blogs`,
      description: truncatedDescription,
      keywords: blog.seo?.metaKeywords?.length
        ? blog.seo.metaKeywords
        : focusKeywords,
      authors: [
        {
          name: authorName,
          url: blog.author?._id
            ? `${SITE_URL}/authors/${blog.author._id.toString()}`
            : undefined,
        },
      ],
      creator: authorName,
      publisher: "Sanatan Blogs",
      category: blog.category,
      robots: {
        index: true,
        follow: true,
        googleBot: {
          index: true,
          follow: true,
          "max-video-preview": -1,
          "max-image-preview": "large",
          "max-snippet": -1,
        },
      },
      openGraph: {
        title: blog.title,
        description: blog.excerpt,
        url: shareUrl,
        siteName: "Sanatan Blogs",
        images: [
          {
            url: imageUrl,
            width: 1200,
            height: 630,
            alt: blog.title,
          },
        ],
        locale: "en_US",
        type: "article",
        publishedTime,
        modifiedTime,
        authors: [authorName],
        section: blog.category,
        tags: blog.tags,
      },
      twitter: {
        card: "summary_large_image",
        site: "@sanatan_blogs",
        creator: "@sanatan_blogs",
        title: blog.title,
        description: truncatedDescription,
        images: [imageUrl],
      },
      alternates: {
        // Always the same URL for a given article, whichever of its two URLs
        // was requested. The hi-IN alternate that used to sit here pointed at
        // /hi/blogs/..., a route this site does not have.
        canonical,
      },
      other: {
        "article:author": authorName,
        "article:published_time": publishedTime || "",
        "article:modified_time": modifiedTime || "",
        "article:section": blog.category,
        "article:tag": (blog.tags || []).join(", "),
      },
    };
  } catch (error) {
    console.error("Error generating metadata:", error);
    return {
      title: "Blog | Sanatan Blogs",
      description:
        "Discover spiritual wisdom and ancient knowledge on Sanatan Blogs.",
      robots: {
        index: false,
        follow: true,
      },
    };
  }
}
